!
hostname branch6-ce1
!
interface eth1
 ip address 10.1.0.29/31
!
interface eth2
 ip address 172.16.8.1/24
!
interface lo
 ip address 10.0.8.1/32
!
interface vti107
 ip address 10.99.0.15/31
!
router bgp 65509
 bgp router-id 10.0.8.1
 neighbor 10.1.0.28 remote-as 65000
 neighbor 10.99.0.14 remote-as 65503
 !
 address-family ipv4 unicast
  network 10.0.8.1/32
  network 172.16.8.0/24
  neighbor 10.1.0.28 activate
  neighbor 10.99.0.14 activate
 exit-address-family
!
ip route 172.16.8.0/24 eth2
!
line vty
!
