!
hostname hub-ce1
!
interface eth1
 ip address 10.1.0.17/31
!
interface eth2
 ip address 172.16.2.1/24
!
interface lo
 ip address 10.0.2.3/32
!
interface vti100
 ip address 10.99.0.0/31
!
interface vti101
 ip address 10.99.0.10/31
!
interface vti102
 ip address 10.99.0.2/31
!
interface vti103
 ip address 10.99.0.4/31
!
interface vti104
 ip address 10.99.0.6/31
!
interface vti105
 ip address 10.99.0.8/31
!
interface vti106
 ip address 10.99.0.12/31
!
interface vti107
 ip address 10.99.0.14/31
!
router bgp 65503
 bgp router-id 10.0.2.3
 timers bgp 60 180
 neighbor 10.1.0.16 remote-as 65000
 neighbor 10.99.0.1 remote-as 65501
 neighbor 10.99.0.3 remote-as 65506
 neighbor 10.99.0.5 remote-as 65507
 neighbor 10.99.0.7 remote-as 65508
 neighbor 10.99.0.9 remote-as 65504
 neighbor 10.99.0.11 remote-as 65502
 neighbor 10.99.0.13 remote-as 65505
 neighbor 10.99.0.15 remote-as 65509
 !
 address-family ipv4 unicast
  network 10.0.2.3/32
  network 172.16.2.0/24
  neighbor 10.1.0.16 activate
  neighbor 10.99.0.1 route-reflector-client
  neighbor 10.99.0.1 activate
  neighbor 10.99.0.3 route-reflector-client
  neighbor 10.99.0.3 activate
  neighbor 10.99.0.5 route-reflector-client
  neighbor 10.99.0.5 activate
  neighbor 10.99.0.7 route-reflector-client
  neighbor 10.99.0.7 activate
  neighbor 10.99.0.9 route-reflector-client
  neighbor 10.99.0.9 activate
  neighbor 10.99.0.11 route-reflector-client
  neighbor 10.99.0.11 activate
  neighbor 10.99.0.13 route-reflector-client
  neighbor 10.99.0.13 activate
  neighbor 10.99.0.15 route-reflector-client
  neighbor 10.99.0.15 activate
 exit-address-family
!
ip route 172.16.2.0/24 eth2
!
line vty
!
