!
hostname dc2-p1
!
interface eth1
 ip address 10.1.0.1/31
 mpls ldp
!
interface eth2
 ip address 10.1.0.4/31
 mpls ldp
!
interface eth3
 ip address 10.1.0.8/31
 mpls ldp
!
interface lo
 ip address 10.0.1.1/32
!
router ospf
 router-id 10.0.1.1
 network 10.0.1.1/32 area 0.0.0.0
 network 10.1.0.1/31 area 0.0.0.0
 network 10.1.0.4/31 area 0.0.0.0
 network 10.1.0.8/31 area 0.0.0.0
!
mpls ldp
 router-id 10.0.1.1
 transport-address 10.0.1.1
!
line vty
!
