!
hostname dc1-pe1
!
vrf_backend netns
!
vrf VRF-CORP
!
vrf VRF-FINANCE
!
vrf VRF-GUEST
!

interface eth1
 ip address 10.1.0.7/31
 mpls ldp
!
interface eth2
 ip address 10.1.0.12/31
 vrf VRF-CORP
!
interface eth3
 ip address 10.1.0.24/31
 vrf VRF-CORP
!
interface lo
 ip address 10.0.0.2/32
!
router ospf
 router-id 10.0.0.2
 network 10.0.0.2/32 area 0.0.0.0
 network 10.1.0.7/31 area 0.0.0.0
!
router bgp 65000
 bgp router-id 10.0.0.2
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.1.2 update-source lo
 neighbor 10.0.2.2 remote-as 65000
 neighbor 10.0.2.2 update-source lo
 !
 address-family ipv4 unicast
  network 10.0.0.2/32
 exit-address-family
 !
 address-family vpnv4 unicast
  neighbor 10.0.1.2 activate
  neighbor 10.0.2.2 activate
 exit-address-family
 !
 address-family ipv4 vrf VRF-CORP
  neighbor 10.1.0.13 remote-as 65501
  neighbor 10.1.0.13 activate
  neighbor 10.1.0.25 remote-as 65504
  neighbor 10.1.0.25 activate
 exit-address-family
 !
 address-family ipv4 vrf VRF-FINANCE
 exit-address-family
 !
 address-family ipv4 vrf VRF-GUEST
 exit-address-family
!
mpls ldp
 router-id 10.0.0.2
 transport-address 10.0.0.2
!
line vty
!
