!
hostname dc2-pe1
!
vrf_backend netns
!
vrf VRF-CORP
!
vrf VRF-FINANCE
!
vrf VRF-GUEST
!

interface eth1
 ip address 10.1.0.9/31
 mpls ldp
!
interface eth2
 ip address 10.1.0.14/31
 vrf VRF-FINANCE
!
interface eth3
 ip address 10.1.0.26/31
 vrf VRF-FINANCE
!
interface lo
 ip address 10.0.1.2/32
!
router ospf
 router-id 10.0.1.2
 network 10.0.1.2/32 area 0.0.0.0
 network 10.1.0.9/31 area 0.0.0.0
!
router bgp 65000
 bgp router-id 10.0.1.2
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.2.2 remote-as 65000
 neighbor 10.0.2.2 update-source lo
 !
 address-family ipv4 unicast
  network 10.0.1.2/32
 exit-address-family
 !
 address-family vpnv4 unicast
  neighbor 10.0.0.2 activate
  neighbor 10.0.2.2 activate
 exit-address-family
 !
 address-family ipv4 vrf VRF-CORP
 exit-address-family
 !
 address-family ipv4 vrf VRF-FINANCE
  neighbor 10.1.0.15 remote-as 65502
  neighbor 10.1.0.15 activate
  neighbor 10.1.0.27 remote-as 65505
  neighbor 10.1.0.27 activate
 exit-address-family
 !
 address-family ipv4 vrf VRF-GUEST
 exit-address-family
!
mpls ldp
 router-id 10.0.1.2
 transport-address 10.0.1.2
!
line vty
!
