FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    iperf3 \
    mgen \
    iproute2 \
    tcpdump \
    net-tools \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir scapy pyftpdlib smbprotocol dnslib
