[agent]
  interval = "15s"
  flush_interval = "15s"
  hostname = "netoracle-telegraf"
  omit_hostname = false

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = []
  timeout = "10s"
  perdevice = true
  total = true

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "overlay", "squashfs"]

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]

[[inputs.net]]
  interfaces = ["eth*"]

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  export_timestamps = true
