!
hostname dc1-ce1
!
interface eth1
 ip address 10.1.0.13/31
!
interface eth2
 ip address 172.16.0.1/24
!
interface lo
 ip address 10.0.0.3/32
!
interface vti100
 ip address 10.99.0.1/31
!
router bgp 65501
 bgp router-id 10.0.0.3
 neighbor 10.1.0.12 remote-as 65000
 neighbor 10.99.0.0 remote-as 65503
 !
 address-family ipv4 unicast
  network 10.0.0.3/32
  network 172.16.0.0/24
  neighbor 10.1.0.12 activate
  neighbor 10.99.0.0 activate
 exit-address-family
!
ip route 172.16.0.0/24 eth2
!
line vty
!
